%% Creating and Plotting histograms in Matlab
% Author: Priam Pillai, Instructor 2.671
% Massachusetts Institute of Technology
% Cambridge, MA 02139

% This function plots a histogram of random data

% Copyright 2010, All Rights Reserved
% 

%%
close all; clear all; clc; % Clear all data and close all windows.
% Plot a histogram of a normal random distribution of number generated by
% randn
figure
hist(randn([100000, 1]),100)


%%
y=1+1*randn([10000,1]); % generate a random variable with non-zero mean and standard deviation
[n xout]= hist(y,100);

cftool(xout,n)

%%